### ISSUE TITLE
Allow Collector to startup without specifying a valid installation_token

### ISSUE THREAD

**Issue by EddieEldridge** [SumoLogic/sumologic-otel-collector#1029]
**Issue**
The Collector refuses to start without a valid installation_token

```
Error: failed to start extensions: collector registration failed: failed to register the collector, got HTTP status code: 401
2023/03/01 14:00:13 collector server run finished with error: failed to start extensions: collector registration failed: failed to register the collector, got HTTP status code: 401
```

**Use Case**
We want to be able to run the Collector locally without the use of a valid installation token. This is very useful where you are manually instrumenting an application and wish to verify the data is being ingested/processed by the Collector locally. We don't want every person who wants to do this to have to use a valid SumoLogic installation token. 

**Proposal**
As preventing the Collector from starting due to an invalid or invalid token is a valid use case, gate the checking of this token behind some kind of flag in the config.

**Example**
```yml
# ==================================
#             EXTENSIONS
# ==================================
extensions:
  sumologic:
    validate_token: false # New Field
    collector_name: local-collector
    collector_fields:
      service_name: local-collector
    installation_token: NO_TOKEN_NECESSARY
```
