### ISSUE TITLE
Limit Log Collection to Specific Kubernetes Namespaces

### ISSUE THREAD

**Issue by HarishKM7** [SumoLogic/sumologic-otel-collector#1183]
I [installed](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/release-v3.9/docs/installation.md) Sumo Logic Helm chart v3.9.1 in an Amazon EKS 1.24 cluster with these Helm values:

```yaml
sumologic:
  accessId: ...
  accessKey: ...
  clusterName: eks-sandbox
  setup:
    monitors:
      enabled: false
    dashboards:
      enabled: false
  collector:
    sources:
      metrics: {}
      events: {}
      traces: {}
  events:
    enabled: false
  logs:
    container:
      excludeNamespaceRegex: ^(?!ingress-nginx).*$
    systemd:
      enabled: false
  metrics:
    enabled: false
  traces:
    enabled: false
fluentd:
  persistence:
    enabled: false
  logs:
    autoscaling:
      enabled: true
    kubelet:
      enabled: false
    systemd:
      enabled: false
  metrics:
    enabled: false
kube-prometheus-stack:
  enabled: false
otelcolInstrumentation:
  enabled: false
metadata:
  persistence:
    enabled: false
  metrics:
    enabled: false
  logs:
    autoscaling:
      enabled: true
tracesGateway:
  enabled: false
otellogs:
  metrics:
    enabled: false
```

My intention is to disable everything except container log collection. The `excludeNamespaceRegex` above is designed to collect logs only from the `ingress-nginx` namespace & avoid all other namespaces.

However, after deploying the chart, pods of the `StatefulSet` `sumo-logic-sumologic-otelcol-logs` started failing with the error:

```
Cannot compile regular expression: ^(?!ingress-nginx).*$
Error: error parsing regexp: invalid or unsupported Perl syntax: `(?!`
```

The same regex works well in Sumo Logic Helm chart v2.18.1 (it uses FluentD instead of OTelCol).

Everything works well after removing `excludeNamespaceRegex` from Helm values. Logs from all namespaces are successfully sent to Sumo, as expected.

According to a few online Perl regex testers I tried, the regex `^(?!ingress-nginx).*$` is valid & matches everything except `ingress-nginx`, as expected.

Is there another Helm value where I can whitelist the namespaces I need, instead of using `excludeNamespaceRegex` to blacklist all namespaces except the ones I need?

If not, how can I fix the above regex to collect logs only from containers in the `ingress-nginx` namespace?

**Comment by kkujawa-sumo** [comment]
```
sumologic:
  logs:
    container:
      excludeNamespaceRegex: ^(?!ingress-nginx).*$
```
sets `exclude` in configuration for [source processor](https://github.com/SumoLogic/sumologic-otel-collector/tree/main/pkg/processor/sourceprocessor): 

```
      source/containers:
        annotation_prefix: pod_annotations_
        collector: eks-sandbox
        container_annotations:
          enabled: false
          prefixes: []
        exclude:
          container: ""
          namespace: ^(?!ingress-nginx).*$$
          node: ""
          pod: ""
        pod_key: pod
        pod_name_key: pod_name
        pod_template_hash_key: pod_labels_pod-template-hash
        source_category: '%{namespace}/%{pod_name}'
        source_category_prefix: kubernetes/
        source_category_replace_dash: /
        source_host: ""
        source_name: '%{namespace}.%{pod}.%{container}'
```
source processor is written in Go and uses [regexp.Compile ](https://pkg.go.dev/regexp#Compile)(in [this](https://github.com/SumoLogic/sumologic-otel-collector/blob/727558f5fb91fd22e6a5d15f7e488b1bc7789c44/pkg/processor/sourceprocessor/source_processor.go#L83) code line)
so it is recommend to use online Go regex testers to test regular expressions (I don't know why the error message says about perl, maybe because Go uses "same semantics that Perl, Python, and other implementations use" - this comes from [regexp.Compile documentation](https://pkg.go.dev/regexp#Compile))

I've found also that the syntax that you've tried to use in configuration (`^(?!ingress-nginx).*$`) is supported in [regexp2](https://github.com/dlclark/regexp2) but regexp2 is not used in source processor, I've found also comparison of `regexp` and `regexp2`: https://github.com/dlclark/regexp2#compare-regexp-and-regexp2

Probably the easiest method to exclude namespaces from which you don't want to collect logs is to list these namespaces in regular expression or patterns for these namespaces.

Another way to collect logs only from desired namespace/namespaces is to modify configuration for `otelcol-logs-collector`, using `otellogs.config.merge` (see [this]( https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/docs/collecting-container-logs.md#direct-configuration) section) to set the path for container logs, current form of configuration:
```
    receivers:
      filelog/containers:
        include:
        - /var/log/pods/*/*/*.log
        ...
```
and use the fact that names of directories in `/var/log/pods`start with namespace

**Comment by HarishKM7** [comment]
Thanks @kkujawa-sumo for the detailed explanation & for the `regexp` & `regexp2` comparison link. As noted [there](https://github.com/dlclark/regexp2#compare-regexp-and-regexp2), negative lookahead `(?!re)` is not supported in `regexp`, so it's basically impossible to create a regex that can match everything except a specific namespace name (also see [this](https://stackoverflow.com/questions/38933898/error-parsing-regexp-invalid-or-unsupported-perl-syntax) StackOverflow answer).

Since other namespaces in my cluster are dynamic, I can't use a regex to filter them out by name. So, I've added this to my Helm values:

```yaml
otellogs:
  config:
    merge:
      receivers:
        filelog/containers:
          include:
          # Collect logs ONLY from these namespaces:
          - /var/log/pods/ingress-nginx_*/*/*.log
```

and it works as expected. I'm now sending logs ONLY from the `ingress-nginx` namespace to Sumo!
