### ISSUE TITLE
sumologicschemaprocessor: possible conflict during attributes aggregation

### ISSUE THREAD

**Issue by sumo-drosiek** [SumoLogic/sumologic-otel-collector#1263]
There is possible conflict within attributes aggregation for the following configuration:

```
processors:
  sumologic_schema:
    aggregate_attributes:
      - attribute: <attribute>
        prefixes:
          - foo_
          - foo2_
```

and the following attributes:

```
foo_bar
foo2_bar
```

Both of them are going to be added as `bar` to the `<attribute>`, which results in undefined behavior
