### ISSUE TITLE
[sourceprocessor] `sourceCategoryPrefix` is not subject to templating

### ISSUE THREAD

**Issue by aboguszewski-sumo** [SumoLogic/sumologic-otel-collector#1322]
Templates don't work in `sourceCategoryPrefix` in `sourceprocessor`.

In otelcol, we use templating before adding the prefix:
https://github.com/SumoLogic/sumologic-otel-collector/blob/da04b70115f8d204871bc1aa744c131dfa4f2f60/pkg/processor/sourceprocessor/source_category_filler.go#L87

However, fluentd first adds the prefix and then inserts templates: 
https://github.com/SumoLogic/sumologic-kubernetes-fluentd/blob/a9dde82a48069f54721cdeb8a45f7bdccf2e057a/fluent-plugin-kubernetes-sumologic/lib/fluent/plugin/filter_kubernetes_sumologic.rb#L213

**Comment by Shadowssong** [comment]
hey @aboguszewski-sumo thanks for adding this bug.  Fwiw I was able to get this working with:

```
  otelcol:
    extraProcessors:
      - transform/addPrefix:
          log_statements:
            - context: resource
              statements:
                - set(attributes["sourceCategory"], Concat([attributes["pod_labels_<yourlabelhere>"], attributes["sourceCategory"]], "/"))
 ```
