### ISSUE TITLE
Support configuration thru environment variable

### ISSUE THREAD

**Issue by mat-rumian** [SumoLogic/sumologic-otel-collector#361]
It should be possible to configure OTEL Collector thru environment variable. This shouldn't require a lot of development effort - please see [AWS Otel Collector solution](https://github.com/aws-observability/aws-otel-collector/blob/main/pkg/config/config_factory.go). Thanks to this functionality we will **simplify a lot** deployments on the environments like AWS ECS Fargate/EC2.

**Comment by pmalek-sumo** [comment]
Ideally we'd work to put this in upstream because in order to introduce this into our collector we'd need to copy paste unexported `func`s (like `getConfigFlag()` or `getSetFlag()` which are used in [here](https://github.com/open-telemetry/opentelemetry-collector/blob/3db1d1146483ba5f8318c895ea2c28a6f8dbd243/service/command.go#L33) which is being used by the code generated with opentelemetry collector builder).

@mat-rumian Are you aware of any issues upstream that tried to track this?

**Comment by mat-rumian** [comment]
Collector supports configuration via environment variable. E.g.

```
export VALID_YAML="    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      otlp:
        endpoint: "otela-collector.default:4317"
        tls:
          insecure: true
        sending_queue:
          num_consumers: 4
          queue_size: 100
        retry_on_failure:
          enabled: true
    processors:
      batch:
      memory_limiter:
        limit_mib: 400
        spike_limit_mib: 100
        check_interval: 5s
    extensions:
      zpages: {}
      memory_ballast:
        size_mib: 165
    service:
      extensions: [zpages, memory_ballast]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp]"
 ```

collector cmd line `./otelcol --config=env:VALID_YAML`
