### ISSUE TITLE
[k8sprocessor] implicit dependencies between owner metadata

### ISSUE THREAD

**Issue by astencel-sumo** [SumoLogic/sumologic-otel-collector#512]
OT distro version: 0.0.57-beta.0

### Steps to reproduce

1. Configure `k8s_tagger` processor with `owner_lookup_enabled: true` and with extract metadata section that includes `deploumentName` but does not include `replicaSetName`, and with `cronJobName` but without `jobName`.

  ```yaml
  processors:
    k8s_tagger:
      owner_lookup_enabled: true
      extract:
        metadata:
         - deploymentName
         - cronJobName
  ```
2. Prepare a Kubernetes cluster that includes a Deployment and a CronJob.
2. Run the collector in a Kubernetes cluster with log and/or metrics collection from pods, observe the metadata on the logs and/or metrics.

### Actual result

- Data from pods that belong to a Deployment is not tagged with deployment name
- Data from pods that belong to a CronJob is not tagged with the cronjob's name

### Expected result

- Data from pods that belong to a Deployment is tagged with deployment name `k8s.deployment.name`
- Data from pods that belong to a CronJob is tagged with the cronjob's name `k8s.cronjob.name`

### How to fix

This is because the Pods that belong to a Deployment actually belong to a ReplicaSet, and that ReplicaSet belongs to the Deployment. With the above configuration, currently the ReplicaSet information is not retrieved from k8s API server, which it should be when the Deployment extraction is defined.

Same with CronJob - Job - Pod hierarchy.
