### ISSUE TITLE
Consistent order of configuration sections in docs/examples

### ISSUE THREAD

**Issue by calebhailey** [SumoLogic/sumologic-otel-collector#689]
It would be helpful for new users if we would organize configuration documentation and/or examples _logically_. 

It has been helpful in my own exploration of OpenTelemetry to arrange my configuration files in the same order that the data flows, i.e. `receivers` => `processors` => `exporters` => `[service.]pipelines`. In this same model, I place extensions as modules to be loaded before configuring the observability pipelines. 

```yaml
---
# /etc/otelcol-sumo/config.yaml
extensions: {} # enable OT extensions

receivers: {} # collect data
processors: {} # filter, aggregate/correlate, and enrich data
exporters: {} # send data

service: {} # daemon runtime instructions
```

In [most](https://github.com/SumoLogic/sumologic-otel-collector/blob/main/docs/Configuration.md#basic-configuration) [examples](https://github.com/SumoLogic/sumologic-otel-collector/blob/main/docs/Configuration.md#basic-configuration-for-logs) in our [configuration](https://github.com/SumoLogic/sumologic-otel-collector/blob/main/docs/Configuration.md#basic-configuration-for-metrics) [documentation](https://github.com/SumoLogic/sumologic-otel-collector/blob/main/docs/Configuration.md#putting-it-all-together) we organize these sections in order of `exporters`, `extensions`, `receivers`, and `service` (with no empty `processors` section). In [other](https://github.com/SumoLogic/sumologic-otel-collector/blob/main/docs/Configuration.md#authentication) [examples](https://github.com/SumoLogic/sumologic-otel-collector/blob/main/docs/Configuration.md#setting-source-category-with-the-resource-processor) we use other orders, which is inconsistent at best and confusing for new users at worst.

It would be great if we restructured the examples in our documentation to consistently order configuration sections. 👌 🙏
